# Generated by Django 4.2.5 on 2023-09-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiyAPP', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bemor',
            name='sana',
            field=models.DateField(blank=True, null=True),
        ),
    ]
